// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SmmAnalyzerPrototype.Data.Data;

#nullable disable

namespace SmmAnalyzerPrototype.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413150022_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.AnalysisResult", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("EngagementForecast")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engagement_forecast");

                    b.Property<DateTime?>("GrammarCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grammar_checked_at");

                    b.Property<bool?>("HasRegulationViolations")
                        .HasColumnType("boolean")
                        .HasColumnName("has_regulation_violations");

                    b.Property<string>("RecommendationsJson")
                        .HasColumnType("text")
                        .HasColumnName("recommendations_json");

                    b.Property<DateTime?>("RegulationCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("regulation_checked_at");

                    b.Property<string>("RegulationComment")
                        .HasColumnType("text")
                        .HasColumnName("regulation_comment");

                    b.Property<string>("StyleAssessment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("style_assessment");

                    b.Property<DateTime?>("StyleCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("style_checked_at");

                    b.Property<string>("StyleIssuesJson")
                        .HasColumnType("text")
                        .HasColumnName("style_issues_json");

                    b.Property<string>("StyleRecommendationsJson")
                        .HasColumnType("text")
                        .HasColumnName("style_recommendations_json");

                    b.Property<string>("StyleStrengthsJson")
                        .HasColumnType("text")
                        .HasColumnName("style_strengths_json");

                    b.Property<string>("StyleSummary")
                        .HasColumnType("text")
                        .HasColumnName("style_summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PostId");

                    b.ToTable("analysis_results");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StyleProfile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("communities");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.CommunityPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Comments")
                        .HasColumnType("integer");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Reposts")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("community_posts");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.GrammarError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<string>("Fragment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspicious");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("grammar_errors");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.ProhibitedTopicMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("RegulationRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("regulation_ref");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("prohibited_topic_matches");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.RegulationChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("RegulationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegulationId");

                    b.ToTable("regulation_chunks");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.RegulationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("regulation_documents");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.AnalysisResult", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.Post", "Post")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("SmmAnalyzerPrototype.Data.Models.AnalysisResult", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.CommunityPost", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.Community", "Community")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.GrammarError", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("GrammarErrors")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.Post", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmmAnalyzerPrototype.Data.Models.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmmAnalyzerPrototype.Data.Models.User", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.Navigation("Author");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.ProhibitedTopicMatch", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("ProhibitedTopicMatches")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.RegulationChunk", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.RegulationDocument", "Regulation")
                        .WithMany("Chunks")
                        .HasForeignKey("RegulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.RegulationDocument", b =>
                {
                    b.HasOne("SmmAnalyzerPrototype.Data.Models.Community", "Community")
                        .WithMany("RegulationDocuments")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.AnalysisResult", b =>
                {
                    b.Navigation("GrammarErrors");

                    b.Navigation("ProhibitedTopicMatches");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.Community", b =>
                {
                    b.Navigation("CommunityPosts");

                    b.Navigation("Posts");

                    b.Navigation("RegulationDocuments");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.Post", b =>
                {
                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.RegulationDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("SmmAnalyzerPrototype.Data.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
